const std = @import("std");
pub fn build(b: *std.Build) void {
    const sdk_build = b.lazyImport(@This(), "r4os_sdk") orelse return;
    const sdk = sdk_build.sdk(b, b.dependencyFromBuildZig(sdk_build, .{}), .{});
    const libraries_build = b.lazyImport(@This(), "r4os_libraries") orelse return;
    const libraries = b.dependencyFromBuildZig(libraries_build, .{});
    const copy_path = libraries.namedLazyPath("r4amd_copy");
    const pm4_path = libraries.namedLazyPath("r4amd_pm4");
    const binding_path = libraries.namedLazyPath("r4amd_zig_binding");
    const driver_path = libraries.namedLazyPath("r4amd_driver");
    const edid_path = libraries.namedLazyPath("r4gfx_edid");
    const render_build = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    render_build.addFileArg(libraries.namedLazyPath("r4amd_native_build"));
    render_build.addArg("-OutputRoot");
    const render_archives = render_build.addOutputDirectoryArg("render-native");
    render_build.has_side_effects = true;
    const native = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    native.addFileArg(b.path("Tools/BuildPort.ps1"));
    native.addArg("-OutputRoot");
    const dcn_archives = native.addOutputDirectoryArg("dcn-native");
    native.has_side_effects = true;
    const artifact = sdk.addR4MFWithOptions(b.path("module.R4MF"), .{ .zig_module_roots = &.{ copy_path, binding_path, pm4_path, driver_path, edid_path }, .native_archives = &.{ render_archives.path(b, "R4AMD-Addr.a"), dcn_archives.path(b, "AMDGPU-DCN1.a") } });
    const verify = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    verify.addFileArg(b.path("Tools/VerifyIdentity.ps1"));
    verify.has_side_effects = true;
    artifact.code.generated.file.step.dependOn(&verify.step);
    const memory_check = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    memory_check.addFileArg(b.path("Tools/VerifyMemory.ps1"));
    memory_check.has_side_effects = true;
    memory_check.step.dependOn(&verify.step);
    artifact.code.generated.file.step.dependOn(&memory_check.step);
    const queue_check = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    queue_check.addFileArg(b.path("Tools/VerifyQueue.ps1"));
    queue_check.has_side_effects = true;
    queue_check.step.dependOn(&verify.step);
    artifact.code.generated.file.step.dependOn(&queue_check.step);
    const start_check = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    start_check.addFileArg(b.path("Tools/VerifyStart.ps1"));
    start_check.has_side_effects = true;
    start_check.step.dependOn(&verify.step);
    artifact.code.generated.file.step.dependOn(&start_check.step);
    const gc_check = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    gc_check.addFileArg(b.path("Tools/VerifyGC.ps1"));
    gc_check.has_side_effects = true;
    gc_check.step.dependOn(&verify.step);
    artifact.code.generated.file.step.dependOn(&gc_check.step);
    const firmware_check = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    firmware_check.addFileArg(b.path("Tools/VerifyFirmware.ps1"));
    firmware_check.has_side_effects = true;
    artifact.code.generated.file.step.dependOn(&firmware_check.step);
    const host = b.createModule(.{ .root_source_file = b.path("src/test.zig"), .target = b.graph.host, .optimize = .ReleaseSafe });
    const host_sdk = sdk.createR4osModule(b.graph.host, .ReleaseSafe);
    host.addImport("r4os", host_sdk);
    host.addImport("r4gfx_edid", b.createModule(.{ .root_source_file = edid_path, .target = b.graph.host, .optimize = .ReleaseSafe }));
    host.addImport("r4amd_copy", b.createModule(.{ .root_source_file = copy_path, .target = b.graph.host, .optimize = .ReleaseSafe }));
    host.addImport("r4amd_pm4", b.createModule(.{ .root_source_file = pm4_path, .target = b.graph.host, .optimize = .ReleaseSafe }));
    const amd_binding = b.createModule(.{ .root_source_file = binding_path, .target = b.graph.host, .optimize = .ReleaseSafe });
    amd_binding.addImport("r4os", host_sdk);
    host.addImport("r4amd", amd_binding);
    const render_driver = b.createModule(.{ .root_source_file = driver_path, .target = b.graph.host, .optimize = .ReleaseSafe });
    render_driver.addImport("r4os", host_sdk);
    render_driver.addImport("r4amd", amd_binding);
    host.addImport("r4amd_driver", render_driver);
    host.addObjectFile(render_archives.path(b, "R4AMD-Addr-Host.a"));
    host.addObjectFile(dcn_archives.path(b, "AMDGPU-DCN1-Host.a"));
    host.addIncludePath(b.path("Port"));
    host.addIncludePath(b.path("ThirdParty/Linux7.2.4/Original/drivers/gpu/drm/amd/include"));
    host.addIncludePath(b.path("src"));
    const samples = b.addWriteFiles();
    const fw = @import("src/firmware.zig");
    var sample_source: std.ArrayList(u8) = .empty;
    sample_source.appendSlice(b.allocator, "pub const files = [_][]const u8{\n") catch @panic("OOM");
    for (0..16) |i| {
        const entry = if (i == 0) fw.Artifact{ .path = "src/firmware_lock.json", .resource = "AMD-FIRMWARE-LOCK.json", .bytes = 0, .sha256 = "", .upstream_path = "", .git_blob = "" } else if (i < 3) fw.lock.metadata[i - 1] else fw.lock.firmware[i - 3].artifact();
        _ = samples.addCopyFile(b.path(entry.path), entry.resource);
        sample_source.appendSlice(b.allocator, b.fmt("    @embedFile(\"{s}\"),\n", .{entry.resource})) catch @panic("OOM");
    }
    sample_source.appendSlice(b.allocator, "};\n") catch @panic("OOM");
    host.addAnonymousImport("firmware_samples", .{ .root_source_file = samples.add("samples.zig", sample_source.items) });
    const tests = b.addTest(.{ .root_module = host });
    tests.step.dependOn(&memory_check.step);
    tests.step.dependOn(&queue_check.step);
    tests.step.dependOn(&start_check.step);
    tests.step.dependOn(&gc_check.step);
    tests.step.dependOn(&firmware_check.step);
    const run = b.addRunArtifact(tests);
    const test_step = b.step("test", "Check AMD owners and linked native render/DCN1 paths");
    test_step.dependOn(&native.step);
    test_step.dependOn(&run.step);
    artifact.output.generated.file.step.dependOn(&run.step);
    const audit = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    audit.addFileArg(b.path("Tools/VerifyFirmware.ps1"));
    audit.addArg("-ContainerPath");
    audit.addFileArg(artifact.output);
    audit.has_side_effects = true;
    b.getInstallStep().dependOn(&audit.step);
}
