//
// Copyright 2008 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// Author: Stanislaw Skowronek
//
// Opcode order and arguments derived from pinned atom.c. No Linux runtime.
pub const Operation = enum { invalid, move, bit_and, bit_or, shift_left, shift_right, mul, div, add, sub, setport, setregblock, setfbbase, compare, switch_case, jump, test_bits, delay, calltable, repeat, clear, nop, eot, mask, postcard, beep, savereg, restorereg, setdatablock, bit_xor, shl, shr, debug, processds, mul32, div32 };
pub const table = [_]struct { operation: Operation, arg: u8 }{
    .{ .operation = .invalid, .arg = 0 },
    .{ .operation = .move, .arg = 0 },
    .{ .operation = .move, .arg = 1 },
    .{ .operation = .move, .arg = 2 },
    .{ .operation = .move, .arg = 3 },
    .{ .operation = .move, .arg = 6 },
    .{ .operation = .move, .arg = 7 },
    .{ .operation = .bit_and, .arg = 0 },
    .{ .operation = .bit_and, .arg = 1 },
    .{ .operation = .bit_and, .arg = 2 },
    .{ .operation = .bit_and, .arg = 3 },
    .{ .operation = .bit_and, .arg = 6 },
    .{ .operation = .bit_and, .arg = 7 },
    .{ .operation = .bit_or, .arg = 0 },
    .{ .operation = .bit_or, .arg = 1 },
    .{ .operation = .bit_or, .arg = 2 },
    .{ .operation = .bit_or, .arg = 3 },
    .{ .operation = .bit_or, .arg = 6 },
    .{ .operation = .bit_or, .arg = 7 },
    .{ .operation = .shift_left, .arg = 0 },
    .{ .operation = .shift_left, .arg = 1 },
    .{ .operation = .shift_left, .arg = 2 },
    .{ .operation = .shift_left, .arg = 3 },
    .{ .operation = .shift_left, .arg = 6 },
    .{ .operation = .shift_left, .arg = 7 },
    .{ .operation = .shift_right, .arg = 0 },
    .{ .operation = .shift_right, .arg = 1 },
    .{ .operation = .shift_right, .arg = 2 },
    .{ .operation = .shift_right, .arg = 3 },
    .{ .operation = .shift_right, .arg = 6 },
    .{ .operation = .shift_right, .arg = 7 },
    .{ .operation = .mul, .arg = 0 },
    .{ .operation = .mul, .arg = 1 },
    .{ .operation = .mul, .arg = 2 },
    .{ .operation = .mul, .arg = 3 },
    .{ .operation = .mul, .arg = 6 },
    .{ .operation = .mul, .arg = 7 },
    .{ .operation = .div, .arg = 0 },
    .{ .operation = .div, .arg = 1 },
    .{ .operation = .div, .arg = 2 },
    .{ .operation = .div, .arg = 3 },
    .{ .operation = .div, .arg = 6 },
    .{ .operation = .div, .arg = 7 },
    .{ .operation = .add, .arg = 0 },
    .{ .operation = .add, .arg = 1 },
    .{ .operation = .add, .arg = 2 },
    .{ .operation = .add, .arg = 3 },
    .{ .operation = .add, .arg = 6 },
    .{ .operation = .add, .arg = 7 },
    .{ .operation = .sub, .arg = 0 },
    .{ .operation = .sub, .arg = 1 },
    .{ .operation = .sub, .arg = 2 },
    .{ .operation = .sub, .arg = 3 },
    .{ .operation = .sub, .arg = 6 },
    .{ .operation = .sub, .arg = 7 },
    .{ .operation = .setport, .arg = 0 },
    .{ .operation = .setport, .arg = 1 },
    .{ .operation = .setport, .arg = 2 },
    .{ .operation = .setregblock, .arg = 0 },
    .{ .operation = .setfbbase, .arg = 0 },
    .{ .operation = .compare, .arg = 0 },
    .{ .operation = .compare, .arg = 1 },
    .{ .operation = .compare, .arg = 2 },
    .{ .operation = .compare, .arg = 3 },
    .{ .operation = .compare, .arg = 6 },
    .{ .operation = .compare, .arg = 7 },
    .{ .operation = .switch_case, .arg = 0 },
    .{ .operation = .jump, .arg = 2 },
    .{ .operation = .jump, .arg = 5 },
    .{ .operation = .jump, .arg = 3 },
    .{ .operation = .jump, .arg = 0 },
    .{ .operation = .jump, .arg = 4 },
    .{ .operation = .jump, .arg = 1 },
    .{ .operation = .jump, .arg = 6 },
    .{ .operation = .test_bits, .arg = 0 },
    .{ .operation = .test_bits, .arg = 1 },
    .{ .operation = .test_bits, .arg = 2 },
    .{ .operation = .test_bits, .arg = 3 },
    .{ .operation = .test_bits, .arg = 6 },
    .{ .operation = .test_bits, .arg = 7 },
    .{ .operation = .delay, .arg = 1 },
    .{ .operation = .delay, .arg = 0 },
    .{ .operation = .calltable, .arg = 0 },
    .{ .operation = .repeat, .arg = 0 },
    .{ .operation = .clear, .arg = 0 },
    .{ .operation = .clear, .arg = 1 },
    .{ .operation = .clear, .arg = 2 },
    .{ .operation = .clear, .arg = 3 },
    .{ .operation = .clear, .arg = 6 },
    .{ .operation = .clear, .arg = 7 },
    .{ .operation = .nop, .arg = 0 },
    .{ .operation = .eot, .arg = 0 },
    .{ .operation = .mask, .arg = 0 },
    .{ .operation = .mask, .arg = 1 },
    .{ .operation = .mask, .arg = 2 },
    .{ .operation = .mask, .arg = 3 },
    .{ .operation = .mask, .arg = 6 },
    .{ .operation = .mask, .arg = 7 },
    .{ .operation = .postcard, .arg = 0 },
    .{ .operation = .beep, .arg = 0 },
    .{ .operation = .savereg, .arg = 0 },
    .{ .operation = .restorereg, .arg = 0 },
    .{ .operation = .setdatablock, .arg = 0 },
    .{ .operation = .bit_xor, .arg = 0 },
    .{ .operation = .bit_xor, .arg = 1 },
    .{ .operation = .bit_xor, .arg = 2 },
    .{ .operation = .bit_xor, .arg = 3 },
    .{ .operation = .bit_xor, .arg = 6 },
    .{ .operation = .bit_xor, .arg = 7 },
    .{ .operation = .shl, .arg = 0 },
    .{ .operation = .shl, .arg = 1 },
    .{ .operation = .shl, .arg = 2 },
    .{ .operation = .shl, .arg = 3 },
    .{ .operation = .shl, .arg = 6 },
    .{ .operation = .shl, .arg = 7 },
    .{ .operation = .shr, .arg = 0 },
    .{ .operation = .shr, .arg = 1 },
    .{ .operation = .shr, .arg = 2 },
    .{ .operation = .shr, .arg = 3 },
    .{ .operation = .shr, .arg = 6 },
    .{ .operation = .shr, .arg = 7 },
    .{ .operation = .debug, .arg = 0 },
    .{ .operation = .processds, .arg = 0 },
    .{ .operation = .mul32, .arg = 1 },
    .{ .operation = .mul32, .arg = 2 },
    .{ .operation = .div32, .arg = 1 },
    .{ .operation = .div32, .arg = 2 },
};
